### ISSUE TITLE
The feature dimensions of the demo program are inconsistent

### ISSUE THREAD

**Issue by ahong007007** [vislearn/ngransac#10]
python3 ngransac_demo.py -img1 images/demo1.jpg -fl1 900 -img2 images/demo2.jpg -fl2 900

Using the code on the official website, the following error occurred

![image](https://user-images.githubusercontent.com/22077027/89535043-73202780-d828-11ea-99fb-bc9695361175.png)

Three variable dimensions are inconsistent

pts1.shape, (2000, 1, 2) ,pts2.shape, (2000, 1, 2) ,ratios.shape (1, 2000, 1)

![image](https://user-images.githubusercontent.com/22077027/89535335-e2961700-d828-11ea-94a2-a48dde6591b0.png)

thanks!

**Comment by ebrach** [comment]
Hi,

I cannot reproduce your error. The tensors `pts1` and `pts2` have the wrong dimensions. They should be (1,2000,2).

https://github.com/vislearn/ngransac/blob/8cd278bd1a6a123076172aa3e04bf65d795b3e9c/ngransac_demo.py#L130-L135

The code above should result in  `pts1` and `pts2` being lists with 2000 entries.

https://github.com/vislearn/ngransac/blob/8cd278bd1a6a123076172aa3e04bf65d795b3e9c/ngransac_demo.py#L139-L140

The code above should turn  `pts1` and `pts2` into tensors of shape (1,2000,2). Particularly, wrapping  `pts1` in a list  `[pts1]` before passing it to  `np.array` should create a tensor with the first axis being one-dimensional. In your case, the first axis is 2000-dimensional. Did you alter the code?

**Comment by xhy3054** [comment]
Hi,
I think i find where is wrong,
`
	pts1 = cv2.undistortPoints(pts1, K1, None)
	pts2 = cv2.undistortPoints(pts2, K2, None)
`
those two lines of code will turn `pts1` and `pts2` from (1,2000,2) to (2000,1,2)

**Comment by ebrach** [comment]
Thanks for the update. Interesting. Which version of OpenCV are you using?

**Comment by xhy3054** [comment]
`opencv-python 4.4.0.42`

**Comment by ebrach** [comment]
At the moment, we can only confirm compatibility to OpenCV 3.4. You might encounter other problems when using Opencv 4.x.
