### ISSUE TITLE
Training taking too long

### ISSUE THREAD

**Issue by MrPositron** [vislearn/ngransac#16]
Hey there! 👋.

When I perform training. Following this command:
```
python ngransac_train_e2e.py -rs -r 0.8 -m weights_init_E_rs_r0.80_.net
```
The time taken for each epoch is about 40-60 mins. Is it normal behavior?
I have found that it takes about 5 seconds to loop over all correspondences. I computed time as following:
```
crs_start = time.time()
for b in range(correspondences.size(0)):
        print(f"Correspondence finding time is {time.time() - crs_start}")
```

**Comment by ebrach** [comment]
Hi,

the training time will depend on your hardware. For end-to-end training it probably depends on the CPU resources available more than the GPU. 40-60mins per epoch is still within the range I would expect - depending on hardware.

Best,
Eric
