### ISSUE TITLE
import problem

### ISSUE THREAD

**Issue by xubangwu** [vislearn/ngransac#20]
hello,I have compiled the ngransac, but when I want to do 'import ngransac',I find the questions as follows:
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/xbw/anaconda3/envs/qg2/lib/python3.7/site-packages/ngransac-0.0.0-py3.7-linux-x86_64.egg/ngransac.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2cv6String8allocateEm

**Comment by ebrach** [comment]
That error might indicate compiler compatibility issues. I.e. the compiler on your system is incompatible with the compiler that compiled OpenCV - presumably you installed pre-compiled packages, e.g. via Conda? Either, 
- you find out which compiler OpenCV was compiled with, and use the same compiler version when compiling NGRANSAC or
- you compile OpenCV from source on your system and point the setup.py to that OpenCV version

**Comment by ebrach** [comment]
Possibly related issue https://github.com/vislearn/ngransac/issues/20

**Comment by ebrach** [comment]
Closing old issue.

**Comment by EdwardjkFeng** [comment]
I've encountered the same issue. I've installed OpenCV (libopencv) via Conda and the issue was not caused by the incompatibility of compiler. It's because I installed OpenCV (version=4.5.5) and the header files are under `include/opencv4/`. Problem solve by changing 
```
opencv_inc_dir = conda_env + '/include'
```
to 
```
opencv_inc_dir = conda_env + '/include/opencv4'
```
in `setup.py`. Hope it helps.
