### ISSUE TITLE
Question in python prepare_data_kitti.py -ds <kitti_folder> -v train

### ISSUE THREAD

**Issue by shenyehui** [vislearn/ngransac#22]
Dear author, thank you for your work! When I use the command "python prepare_data_kitti.py -ds <kitti_folder> -v train," I encountered the following error. How should I resolve this?

Traceback (most recent call last):
  File "prepare_data_kitti.py", line 184, in <module>
    np.save(out_dir + 'pair_%d_%d.npy' % (img1_idx, img2_idx), [
  File "<__array_function__ internals>", line 200, in save
  File "/opt/ros/noetic/lib/python3/dist-packages/numpy/lib/npyio.py", line 521, in save
    arr = np.asanyarray(arr)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimension. The detected shape was (9,) + inhomogeneous part.

**Comment by ebrach** [comment]
Hi. Are you using the library version recommended, particularly OpenCV 3.4.2?

Best,
Eric

**Comment by shenyehui** [comment]
> Hi. Are you using the library version recommended, particularly OpenCV 3.4.2?
> 
> Best, Eric

Thank you for your response. Changing OpenCV to version 3.4.2 still couldn't solve the problem. In the end, I modified the code to save the data in dictionary format. Is it okay to save it in dictionary format?

**Comment by shenyehui** [comment]
> Hi. Are you using the library version recommended, particularly OpenCV 3.4.2?
> 
> Best, Eric

Thank you for your response. I have resolved the issue; it was due to my numpy version being too high.
