### ISSUE TITLE
compiling and installing C++ extension

### ISSUE THREAD

**Issue by Prishani** [vislearn/ngransac#4]
Hi 

I am having trouble installing installing the C++ component. I have edited the setup.py to point to the correct path of the include and library directories, but after some compiling, I still end up with a link issue:
 fatal error LNK1181: cannot open input file 'opencv_core.lib'
Do you think the problem is with the installation of opencv? I am using pycharm, so I used the IDE to download opencv and its been working well. To install this code, I downloaded opencv for anaconda using conda opencv install instruction.

I am thinking of reinstalling everything, but I am not sure if will solve the issue.

**Comment by ebrach** [comment]
Hi, 

First, make sure that the file opencv_core.lib which seems to be the problem is actually present in the directory that you added to the setup.py as library path.

**Comment by Prishani** [comment]
Hi

The lib file opencv_core.lib does not exist anywhere on the machine. I have uninstalled and reinstalled opencv, and I still cannot find the opencv_core.lib file.
