### ISSUE TITLE
compiling errors

### ISSUE THREAD

**Issue by Prishani** [vislearn/ngransac#6]
Hi

The lib file opencv_core.lib does not exist anywhere on the machine. I have uninstalled and reinstalled opencv, and I still cannot find the opencv_core.lib file.

_Originally posted by @Prishani in https://github.com/vislearn/ngransac/issues/4#issuecomment-558156780_

**Comment by ebrach** [comment]
Hi,

what system are you on, and how exactly did you install OpenCV?

**Comment by Prishani** [comment]
Hi

Thanks for the reply, I am using Windows 10, 64 bit machine. I am using
pycharm 19.2 currently, for my development work. Within pycharm, I
installed the opencv package, by using the settings>pycharm interpreter.
This works well, as I am currently using BRISK, Flann_matcher and RANSAC to
do feature detection and outlier detection. My plan is to try out your code
using BRISK feature detector, as an alternative RANSAC approach.

I am unsure how to use your code in pycharm, so I installed opencv using
anaconda prompt, using the instructions, conda install -c conda-forge opencv
I then set the "CONDA_PREFIX" using the environment variables to point to
the include and lib folder. Last week when I ran the setup file, the code
could not find the path to the header files, and I had to go into each
header file and specify the path. I then ended up with an error that it
could not find the "opencv_core.lib" file. When I checked, it didn't exist
anywhere in any directory. I thought there must have been an installation
error, so I uninstalled Anaconda, opencv and re-installed them again. Now
after running setup.py,  I get an error
"C:\Anaconda\lib\site-packages\torch\lib\include\torch\csrc\api\include\torch/torch.h(7):
fatal error C1021: invalid preprocessor command 'warning''
I am not sure if this means I perhaps need to change my version of opencv
to a lower version.  I am currently using opencv version 4, with python 3.6.

Kind Regards
Prishani

**Comment by ebrach** [comment]
Hi,

I am neither using Windows nor pycharm, so I can only offer limited support. The OpenCV library files have to be somewhere on the system, if you are able to use OpenCV. My best guess is, that they are named differently, for example by having the version number appended to the file name. Just search for "opencv_core" (without the file ending), and see what you find? 

Regarding OpenCV4: I did not try this yet, and cannot comment how many problems this causes. I would recommend first getting it to run with OpenCV 3.4, which is supported, and only then upgrade to OpenCV 4. You install Opencv 3.4 via "conda install -c anaconda opencv" (but remove OpenCV 4 first).

Kind regards,
Eric

**Comment by Prishani** [comment]
> Hi,
> 
> I am neither using Windows nor pycharm, so I can only offer limited support. The OpenCV library files have to be somewhere on the system, if you are able to use OpenCV. My best guess is, that they are named differently, for example by having the version number appended to the file name. Just search for "opencv_core" (without the file ending), and see what you find?
> 
> Regarding OpenCV4: I did not try this yet, and cannot comment how many problems this causes. I would recommend first getting it to run with OpenCV 3.4, which is supported, and only then upgrade to OpenCV 4. You install Opencv 3.4 via "conda install -c anaconda opencv" (but remove OpenCV 4 first).
> 
> Kind regards,
> Eric

**Comment by Prishani** [comment]
Hi

I managed to install ngransac, well I think so! This is the last commands I got back:
Installed c:\anaconda\lib\site-packages\ngransac-0.0.0-py3.7-win-amd64.egg
Processing dependencies for ngransac==0.0.0
Finished processing dependencies for ngransac==0.0.0

I tried to test it by import ngransac at the anaconda prompt terminal window like so:
(base) C:\ngransac-master\ngransac>python
Python 3.7.1 | packaged by conda-forge | (default, Mar 13 2019, 13:32:59) [MSC v.1900 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ngransac
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: DLL load failed: The specified module could not be found.
>>> import numpy
>>>
As you can see, it imports numpy, but not ngransac. I tried it in a new script in Spyder, the IDE for python in Anaconda, and it also did not work.

Any suggestions?

Kind Regards
Prishani

**Comment by ebrach** [comment]
Hi,
I'm not sure I can help, as your general system setup is very different from mine. I would first check the anaconda lib folder to check what it has generated exactly for NG-RANSAC. The import tries to load a DLL file - see whether such a file is in the anaconda folder. If yes, then it is probably a context problem, i.e. the anaconda environment seems not to be loaded by default. (Add it to your path variable?).

**Comment by Prishani** [comment]
Hi

Yes, the two systems is different.  I did manage fix the anaconda
environment error and locate the module to import into pycharm. However, it
was unsuccessful when it tried to import it.
According to the error I get when I import the module:
ERROR: Could not find a version that satisfies the requirement ngransac
(from versions: none)

I will try another IDE, Spyder, and see if I manage to get it working.
If there is anyone you know who is using a similar system to mine, and
could help, please let me know.

My last question was, if I do manage to install and run the demo code, can
I change the feature detector to BRISK when modifying the code to work on
my dataset?

Thank you for all your assistance in this regard.

Kind Regards
Prishani

**Comment by ebrach** [comment]
Yes, changing the detector/descriptor is easy. Just replace the associated constructors for SIFT. Since the OpenCV interfaces for all detectors are similar, it's easy to do.

**Comment by csyhy1986** [comment]
For compiling on windows, I recommend vs2019. If you complied successfully but DLL load failed, you should copy all the related .dll to the directory where your the ngransac.pyd file placed, such as opencv.dlls,  python3.dll, and torch.dlls. There is also another thing should be notice, you may add include<torch/extensions.h> in the head of ngransac.cpp, otherwise it may arise "arguments not support error". 
There are also many other traps for using ngransac on windows, if you still not solved this problem, pls contact me.
Here thanks for the authors again for their solid work.

**Comment by loyata** [comment]
> For compiling on windows, I recommend vs2019. If you complied successfully but DLL load failed, you should copy all the related .dll to the directory where your the ngransac.pyd file placed, such as opencv.dlls, python3.dll, and torch.dlls. There is also another thing should be notice, you may add include<torch/extensions.h> in the head of ngransac.cpp, otherwise it may arise "arguments not support error".
> There are also many other traps for using ngransac on windows, if you still not solved this problem, pls contact me.
> Here thanks for the authors again for their solid work.

Hi, 
I managed to build on windows, but had trouble loading dlls. Could you please give more information about what dlls should be copied to the .pyd directory? I have copied opencv_world340.dll, python3.dll, torch.dll, torch_cpu.dll, torch_cuda.dll, torch_global_deps.dll, torch_python.dll, however, it didn't work.

Thank you a lot!

**Comment by csyhy1986** [comment]
c10.dll, c10_cuda.dll, caffe2_nvrtc.dll should also be copied.

**Comment by ivanshilo** [comment]
One can use [Dependecy Walker](https://github.com/lucasg/Dependencies) to inspect *.pyd file and get a list of missing libraries (Dlls)

The easyest in this case with torch libs would be to copy complete folder will DLLs from "Lib\site-packages\torch\lib" to where ngransac.cp37-win_amd64.pyd is located.

**Comment by ebrach** [comment]
Closing this issue, since its quite old.
