### ISSUE TITLE
How to estimate the camera pose?

### ISSUE THREAD

**Issue by tomjerrygithub** [vislearn/ngransac#9]
How to estimate the camera pose?

**Comment by ebrach** [comment]
I'm happy to help, but I need more context about your question. If you wish to use NG-RANSAC for absolute pose regression (ie camera re-localization) you find that code here: https://github.com/vislearn/ngdsac_camreloc

**Comment by tomjerrygithub** [comment]
> I'm happy to help, but I need more context about your question. If you wish to use NG-RANSAC for absolute pose regression (ie camera re-localization) you find that code here: https://github.com/vislearn/ngdsac_camreloc

thank you .  
If I don’t have camera intrinsic, no focal length. how to estimate camera pose ？


My input is a video stream or sequence of frames ，
I want to track the four points （or more ）in the first frame throughout the sequence of frames, so that I can naturally implant a picture in the video
In the beginning, I used ”ngransac“ to extract features,  matching, and estimate homography. but it's not so good.
i am trying to use pose estimating , but i have no camera intrinsic \  focal length. How can i use ngdsac_camreloc to  estimage camera pose and to achieve my goal ？
thanks very much！

**Comment by ebrach** [comment]
Hi, it sounds like you are looking for a visual odometry system, ie. something more complex than NG-RANSAC (NG-RANSAC could be one ingredient in such a system). Maybe have a look at ORB-SLAM (https://github.com/raulmur/ORB_SLAM2) or related works. 

You could also use this code, ie. NG-RANSAC for fundamental / essential matrix estimation, to get the relative pose from frame to frame. In essence you would be building a visual odometry system yourself. You could use heuristics for the unknown camera intrinsics, e.g. the image center as principal point, and the image diagonal in pixels as focal length.

Hope that helps,
Eric

**Comment by tomjerrygithub** [comment]
> Hi, it sounds like you are looking for a visual odometry system, ie. something more complex than NG-RANSAC (NG-RANSAC could be one ingredient in such a system). Maybe have a look at ORB-SLAM (https://github.com/raulmur/ORB_SLAM2) or related works.
> 
> You could also use this code, ie. NG-RANSAC for fundamental / essential matrix estimation, to get the relative pose from frame to frame. In essence you would be building a visual odometry system yourself. You could use heuristics for the unknown camera intrinsics, e.g. the image center as principal point, and the image diagonal in pixels as focal length.
> 
> Hope that helps,
> Eric

Thanks，i will try. 
if i get the  pose  R & t ,how to transform my points in img1 to  img2 ?  
i'd know how to do this by homography matrix

**Comment by ebrach** [comment]
You construct a 4x4 transformation matrix from R and t, and multiply your points in homogeneous coordinates.

Please use github issues for concrete support concerning the provided code. The questions you ask are better answered by introduction lectures to computer vision or computer graphics.

**Comment by tomjerrygithub** [comment]
> You construct a 4x4 transformation matrix from R and t, and multiply your points in homogeneous coordinates.
> 
> Please use github issues for concrete support concerning the provided code. The questions you ask are better answered by introduction lectures to computer vision or computer graphics.

Thanks

**Comment by tomjerrygithub** [comment]
> You construct a 4x4 transformation matrix from R and t, and multiply your points in homogeneous coordinates.
> 
> Please use github issues for concrete support concerning the provided code. The questions you ask are better answered by introduction lectures to computer vision or computer graphics.

hi，Can you help me? I don't know how to turn a point in a 2D image into a homogeneous coordinate, then if success , multiply it by R, t, and then how to turn it back to 2D point ?
I'm sorry to ask you  questions here. Can we send an email?

**Comment by ebrach** [comment]
Sorry, but I do not have time for this. As I said, there is much introductory material on the topic online that should get you started.
